### ISSUE TITLE
congratulations! 

### ISSUE THREAD

**Issue by wnn2000** [michaelofsbu/SpatialCorrection#1]
congratulations! This is a very good study!

**Comment by michaelofsbu** [comment]
Thank you for your interest!

**Comment by wnn2000** [comment]
I'd like to ask about iterations in A.2 IMPLEMENTATION DETAILS mean the iterations of training? That's say, for isic2017, 10k iterations mean 10 epochs, because batch size is 2 and the training set has 2k images

**Comment by michaelofsbu** [comment]
Yes, it's the iteration of training. But for isic2017, the batch size is set to be 10 according to the parameter we provided in `run.sh`, which indicates epochs of 50. We highly recommend referring to parameters in `run.sh`, which is slightly different from what we mentioned in the paper due to further tuning.
